# Site settings
title: Cylicon Valley
email: info@cyliconvalley.es
#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Charlas

description: > # this means to ignore newlines until "baseurl:"
   Punto de encuentro de todos aquellos grupos relacionados con las nuevas tecnologías que tengan voz dentro de la región de Castilla y León

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cyliconvalley.com" # the base hostname & protocol for your site

disqus: true
disqus_shortname: 'cyliconvalley'
author: CyLicon Valley
twitter_username: cylicon_valley
github_username:  cylicon_valley

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html

